# Preprocesamiento 

## Paso 1: Limpiando el texto

In [3]:
import re

cadena = "When I went to New York,the parking is way too expensive!!,you'll find one for --$, http:centralparking.com-new-yorkwthst.html You can go to this adress to fing good deals. Leave you luggage and go park your cars!"

cadenaLimpia = re.sub('(http(s?):(//)?)?(\w+\.)?(\w+\.\w{3}(/.+)?)',' ',cadena)
print("Cadena sin Link: {}".format(cadenaLimpia))

#cadenaLimpia = re.sub('[^a-zA-Z]',' ',cadenaSinLinks)
#print("Cadena sin otros carecteres: {}".format(cadenaLimpia))


Cadena sin Link: When I went to New York,the parking is way too expensive!!,you'll find one for --$,  -new- l You can go to this adress to fing good deals. Leave you luggage and go park your cars!


## Paso 2: Tokenización, Lemanización o Stemming

## Tokenización

In [4]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+')
words =tokenizer.tokenize(cadenaLimpia)
print(words)

['When', 'I', 'went', 'to', 'New', 'York', 'the', 'parking', 'is', 'way', 'too', 'expensive', 'you', 'll', 'find', 'one', 'for', 'new', 'l', 'You', 'can', 'go', 'to', 'this', 'adress', 'to', 'fing', 'good', 'deals', 'Leave', 'you', 'luggage', 'and', 'go', 'park', 'your', 'cars']


In [18]:
from nltk import word_tokenize
tokens = word_tokenize(cadenaLimpia)
print(tokens)

['When', 'I', 'went', 'to', 'New', 'York', ',', 'the', 'parking', 'is', 'way', 'too', 'expensive', '!', '!', ',', 'you', "'ll", 'find', 'one', 'for', '--', '$', ',', '-new-', 'l', 'You', 'can', 'go', 'to', 'this', 'adress', 'to', 'fing', 'good', 'deals', '.', 'Leave', 'you', 'luggage', 'and', 'go', 'park', 'your', 'cars', '!']


## Limpiando StopWords

In [5]:
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))
print(stopWords)

{'for', 'now', 'at', 'and', 'when', 'needn', 'having', 'all', "she's", 'the', 'more', 'be', 'being', 'very', 'same', 'few', "you'll", "needn't", 'above', 'this', 'yourselves', 'won', "won't", "hadn't", 'because', 'isn', "haven't", 'down', 'just', 'again', 'we', 'doesn', 'below', 'under', 'my', 'shouldn', 'have', 'against', 'both', 'they', 'hadn', "shouldn't", 'then', 'each', 'couldn', 'before', "hasn't", 'as', 'wouldn', 're', 'yours', 'aren', 'will', 'no', "aren't", "you'd", 'his', 'that', 'out', "doesn't", 'hers', 'after', 'don', 'any', 'has', "wasn't", "wouldn't", 'it', 'further', 'off', 'in', 'where', 'o', 'so', 'i', 'are', 'themselves', "mustn't", "mightn't", 'her', "didn't", 'between', 'ourselves', 'do', 'those', "shan't", 'himself', "isn't", 'during', 'of', 'mightn', 'didn', "it's", 'was', 's', 'some', 'them', 'ours', 'll', 'am', 'what', 'myself', 'you', 'who', 'ain', 'mustn', 'herself', 'yourself', 'had', 'how', 'nor', 'through', 'but', "couldn't", 'can', 'own', 'their', 'or', '

In [6]:

tokenCorpus = [word for word in words if not word in stopWords]
print(tokenCorpus)


['When', 'I', 'went', 'New', 'York', 'parking', 'way', 'expensive', 'find', 'one', 'new', 'l', 'You', 'go', 'adress', 'fing', 'good', 'deals', 'Leave', 'luggage', 'go', 'park', 'cars']


## Lemanización

In [7]:
from nltk.stem  import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
corpusLemma = []
for x in tokenCorpus:
    corpusLemma.append(wordnet_lemmatizer.lemmatize(x,pos='v'))
print(corpusLemma)


['When', 'I', 'go', 'New', 'York', 'park', 'way', 'expensive', 'find', 'one', 'new', 'l', 'You', 'go', 'adress', 'fing', 'good', 'deal', 'Leave', 'luggage', 'go', 'park', 'cars']


## Stemming

In [9]:
from nltk.stem.lancaster import LancasterStemmer
LS = LancasterStemmer()
corpus = []
for x in corpusLemma:
    corpus.append(LS.stem(x))
print(corpus)

['when', 'i', 'go', 'new', 'york', 'park', 'way', 'expend', 'find', 'on', 'new', 'l', 'you', 'go', 'adress', 'fing', 'good', 'deal', 'leav', 'lug', 'go', 'park', 'car']


## Creando la bolsa de palabras

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
w = cv.get_feature_names()

print(w)
print("----------------------")
print(X)


['adress', 'car', 'deal', 'expend', 'find', 'fing', 'go', 'good', 'leav', 'lug', 'new', 'on', 'park', 'way', 'when', 'york', 'you']
----------------------
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0

# Creando un modelo para Análisis de Sentimientos

In [11]:
# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd

import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer

import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout

INITIAL = None


## Preprocesando los datos


In [12]:
dataset = pd.read_csv('Restaurant_Reviews.tsv',delimiter='\t',quoting=3)

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import nltk




def getCorpus(data):
    ps = PorterStemmer()
    corpus = []
    for review in data:
        x = re.sub('[^a-zA-Z]',' ',review).lower().split()
        corpus.append(' '.join([ps.stem(word) for word in x if not word in set(stopwords.words('english'))]))
    return corpus

def getWordBag(data):    
    corpus = getCorpus(data)
    maxF = 1500
    cv = CountVectorizer(max_features=maxF)
    X = cv.fit_transform(corpus).toarray()
    
    global INITIAL
    if np.all(INITIAL ==None):
         INITIAL = np.array(corpus)
    if X.shape[1] < maxF:
        y=cv.fit_transform(INITIAL).toarray()
        aux  = [[0]*y.shape[1]]
        w = cv.get_feature_names()
        for word in corpus:
            for y in word.split():
                if y in w:
                    pos = w.index(y)
                    aux[0][pos] = 1
        X = np.array(aux)
    return X

def liked(review):
    if review == [False]:
        return "Comentario Negativo."
    else:
        return "Comentario Positivo."

In [13]:
X = getWordBag(dataset['Review'])
y = dataset['Liked']
X_train , X_test, y_train, y_test = train_test_split(X,y,test_size= 0.25,random_state=0)


## Implementando una red Neuronal


In [14]:
Ann = Sequential()
shape = int(X.shape[1]/2)
print(X.shape)
Ann.add(Dense(units=shape,kernel_initializer='uniform',activation='relu',input_dim=X.shape[1]))
Ann.add(Dropout(0.7))
Ann.add(Dense(units=shape,kernel_initializer='uniform',activation='relu'))
Ann.add(Dropout(0.7))
Ann.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))
        
Ann.compile(optimizer='RMSprop',loss='binary_crossentropy',metrics=['accuracy'])
        
from time import time
        
t0 = time()
Ann.fit(X_train,y_train,batch_size=10,epochs=20)
t1 = time()
print("el tiempo fue: {} minutos".format((t1-t0)/60))
        
        

(1000, 1500)
Epoch 1/20
750/750 [==============================] - 4s 5ms/step - loss: 0.6814 - acc: 0.5827
Epoch 2/20
750/750 [==============================] - 4s 5ms/step - loss: 0.5644 - acc: 0.7480
Epoch 3/20
750/750 [==============================] - 4s 5ms/step - loss: 0.3907 - acc: 0.8320
Epoch 4/20
750/750 [==============================] - 3s 5ms/step - loss: 0.2931 - acc: 0.8773
Epoch 5/20
750/750 [==============================] - 3s 5ms/step - loss: 0.2421 - acc: 0.9013
Epoch 6/20
750/750 [==============================] - 3s 5ms/step - loss: 0.1896 - acc: 0.9200
Epoch 7/20
750/750 [==============================] - 3s 5ms/step - loss: 0.1494 - acc: 0.9360
Epoch 8/20
750/750 [==============================] - 3s 5ms/step - loss: 0.1412 - acc: 0.9507
Epoch 9/20
750/750 [==============================] - 4s 5ms/step - loss: 0.1009 - acc: 0.9560A: 1s - loss: 0
Epoch 10/20
750/750 [==============================] - 4s 5ms/step - loss: 0.0744 - acc: 0.9720
Epoch 11/20
750/750 [

## predicciones y resultados

In [15]:
y_pred = Ann.predict(X_test)
y_pred = (y_pred>0.5)

cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy = ((cm[0][0]+cm[1][1])/X_test.shape[0])*100
print(accuracy)

[[92 25]
 [34 99]]
76.4


## Haciendo una prediccion 

In [16]:
pred = "Service was very prompt"
#pred = "Crust is not good"
X1 = getWordBag([pred])
y1 = Ann.predict(X1) > 0.5
print(liked(y1))


pred = "Honeslty it didn't taste THAT fresh.)"
X1 = getWordBag([pred])
y1 = Ann.predict(X1) > 0.5
print(liked(y1))


Comentario Positivo.
Comentario Negativo.


## Usando Clasificador bayesiano Ingenuo

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)
   
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy = ((cm[0][0]+cm[1][1])/X_test.shape[0])*100
print(accuracy)


[[ 67  50]
 [ 20 113]]
72.0


In [18]:
pred = "Service was very prompt"
X1 = getWordBag([pred])
y1 = classifier.predict(X1) > 0.5
print(liked(y1))

pred = "Honeslty it didn't taste THAT fresh.)"
X1 = getWordBag([pred])
y1 = classifier.predict(X1) > 0.5
print(liked(y1))


Comentario Positivo.
Comentario Negativo.
